[project]
name = "cancellation-task-stim-and-analysis-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "polars>=1.36.1",
    "scipy>=1.16.3",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.5.0",
]
